### ISSUE TITLE
[SDK-2.0.6-beta2] No Success or Failure getting triggered incase of empty messageList

### ISSUE THREAD

**Issue by jeetkapadia** [cometchat-pro/ios-chat-sdk#47]
**Describe the bug**
Success or Failure block not getting triggered incase of the empty message list.

**To Reproduce**
try to fetch message list which has no messages.

**Expected behavior**
It should provide an empty array in the success block.

**Comment by seanchristopherjordan** [comment]
While running the 2.0.6 beta we're also getting the same result. It also happens with different conditions, ie. when the message list has content.  Nothing is returned. 

The only thing that seems to produce any response at all is setting the limit to -1. In which case it throws an error.

**Comment by jeetkapadia** [comment]
Hi @seanchristopherjordan ,

I have tried with the below code in which the array returning was empty and I was able to get the success block.

`var messageRequest = MessagesRequest.MessageRequestBuilder().set(uid:"UID OF MY USER").hideMessagesFromBlockedUsers(true).set(limit: 30).build()`

```
messageRequest.fetchPrevious(onSuccess: { (success) in
            
            print("success of fetchPrevious \(success)")
            
        }) { (error) in
            
            print("here error \(error?.errorDescription)")
        }
```
Please try with the above code and let me know in case if you face any issue. You can also refer our sample app which is present on the below link

https://github.com/cometchat-pro-samples/ios-swift-chat-app

Thanks.

**Comment by aco90ue** [comment]
Hello @jeetkapadia,

Regarding this messageRequest issue, I downloaded your iOS sample app, set up our chat comet apiKey and appId:
- Then I chat between the two, exchanging text messages, then go back to Conversations list
- Re-enter to the previous chatting mate and the list is empty

So, requests I tried and needed are working, but fetching the messages doesn't return anything.

**Comment by jeetkapadia** [comment]
Hi @seanchristopherjordan ,

Have you tried the above code snippet? Also in our ios-swift-sample app, we have written function with name fetchPreviousMessages() which takes messagesRequest as input parameter and the other parameter is completion handler. Inside the fetchPreviousMessages() we have called the messageReq.fetchPrevious() of our SDK which is used for fetching the messageList. On the success of messageReq() we check whether the messages are present or not and it contains the lastMessage or not. If there is no lastmessage present then we return from there and due to which the function written in the sample app i.e fetchPreviousMessages of the sample provides nothing. But the SDK method is running fine. You can try running the above code snippet and you will be able to receive the empty messageList. We will also update our sample app with the changes required.

**Comment by aco90ue** [comment]
Hi @jeetkapadia,

Thats exactly function in the sample app that doesn't return anything. Even tried your code snippet but still nothing.

**Comment by NishantTiwarins** [comment]
Hi @aco90ue 
The function is not returning success or failure due to the following reason 
Scenario :- when there are no messages with the user and you enter ChatScene to send and recieve message.
Steps:- 
1. when you enter the ChatViewController it enters viewDidLoad and fetchPreviousMessages method is called (line 116) i.e (Screenshot 1)
2.This fetchPreviousMessages method goes to line (285) in same ChatViewController and messageRequestBuilder tries to fetch the message (line 287)
3. It enters the success block and checks for the condition (lastMessage = messages.last ) or else it returns. Since there are no messages it goes into return block. (Screenshot 2)
So this is the reason it is not returning success or failure 

I have checked this with CometChat Pro Version 
![Screenshot1](https://user-images.githubusercontent.com/56542484/71622571-9af93e00-2bfc-11ea-9b85-894b06662b0b.png)
![Screenshot2](https://user-images.githubusercontent.com/56542484/71622572-9af93e00-2bfc-11ea-851a-457dc729e5a2.png)

2.0.6-beta2
Have provided below the screenshots of the same in debug mode. Please let us know if you still have doubts and issue

**Comment by aco90ue** [comment]
Hi @NishantTiwarins, 
I found out what's the thing. If MessageRequest or any other Request is global property then it works, but if any request is passed as a constant, let property, inside the function, it doesn't retrieve result. I guess, maybe, .build() is asynchronous or whateever may be the case.
