### ISSUE TITLE
[2.0.8] Cannot find protocol declaration for CometChatPro Delegates in objective c project

### ISSUE THREAD

**Issue by TheikChan** [cometchat-pro/ios-chat-sdk#57]
<img width="1292" alt="Screenshot 2020-05-18 at 11 48 32 AM" src="https://user-images.githubusercontent.com/13691817/82188738-543e8300-9914-11ea-9e37-24d060f4e17e.png">

**Comment by NishantTiwarins** [comment]
Hi @TheikChan 

Can you please run the app on the simulator. The issue you are facing is due to the Xcode bug as it creates a conflicts in a mixed project. Please run the project in the device we will try to remove the issues and provide support for the simulator in future versions. 

Since your query is resolved on the forum have posted the same answer for others so that they can get help. We are closing the issue here.

Thanks,
Nishant
